name = "Gregtech Boiler Blower"
author = "Dr. Beako\u001b[D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "559f504c11e84f28c25f7ca43d724f0747e0e38a17eb1f9d1c774892ed439043"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
