name = "Gregtech Boiler Blower"
author = "Dr. Beako\u001b[D"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cef29076caec6b3845cc5aa1f73c125725f9a2503b6a9bff785de6748d0fe5d0"

[versions]
forge = "14.23.5.2859"
minecraft = "1.12.2"
